language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
before_script: redis-cli ping

script:
  - behave
  - nosetests --verbose --with-coverage --cover-erase --cover-package=server

after_success:
  - coveralls

services:
  - redis-server
