codecov:
  branch: master
  bot: qdm12

coverage:
  precision: 3
  round: nearest
  range: "60...90"

  notify:
    slack:
      default:
        url: https://nyu-devops.slack.com/messages/portfolio2/
        threshold: 0.5
        branches: 
        - master
        attachments: "sunburst, diff"

  status:
    project:
      default:
        target: auto
        threshold: 0.5
        branches:
        - master

  ignore:
  - features/*

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: branch
  behavior: default
